# -*- encoding: utf-8 -*-
from abjad.tools import pitchtools


double_stop_halo_pitches = [
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('g,,'),
            pitchtools.NamedPitch('a,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('af,,'),
            pitchtools.NamedPitch('bf,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('gqs,,'),
            pitchtools.NamedPitch('aqs,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('a,,'),
            pitchtools.NamedPitch('b,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('bqf,,'),
            pitchtools.NamedPitch('cqs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('af,,'),
            pitchtools.NamedPitch('bf,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('gqs,,'),
            pitchtools.NamedPitch('aqs,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('a,,'),
            pitchtools.NamedPitch('b,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('g,,'),
            pitchtools.NamedPitch('a,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('a,,'),
            pitchtools.NamedPitch('b,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('b,,'),
            pitchtools.NamedPitch('cs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('aqs,,'),
            pitchtools.NamedPitch('bqs,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('bf,,'),
            pitchtools.NamedPitch('c'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('g,,'),
            pitchtools.NamedPitch('a,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('a,,'),
            pitchtools.NamedPitch('b,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('b,,'),
            pitchtools.NamedPitch('cs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('aqs,,'),
            pitchtools.NamedPitch('bqs,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('cqf,'),
            pitchtools.NamedPitch('dqf'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('bf,,'),
            pitchtools.NamedPitch('c'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('c,'),
            pitchtools.NamedPitch('d'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('g,,'),
            pitchtools.NamedPitch('a,'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('c,'),
            pitchtools.NamedPitch('d'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('bqf,,'),
            pitchtools.NamedPitch('cqs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('cqs,'),
            pitchtools.NamedPitch('dqs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('d,'),
            pitchtools.NamedPitch('e'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('b,,'),
            pitchtools.NamedPitch('cs'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('c,'),
            pitchtools.NamedPitch('d'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('dqf,'),
            pitchtools.NamedPitch('eqf'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('ef,'),
            pitchtools.NamedPitch('f'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('c,'),
            pitchtools.NamedPitch('d'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('dqf,'),
            pitchtools.NamedPitch('eqf'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('etqf,'),
            pitchtools.NamedPitch('fqf'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    pitchtools.PitchSegment(
        (
            pitchtools.NamedPitch('d,'),
            pitchtools.NamedPitch('e'),
            ),
        item_class=pitchtools.NamedPitch,
        ),
    ]