# -*- encoding: utf-8 -*-
from abjad.tools import datastructuretools
from abjad.tools import indicatortools
from abjad.tools import instrumenttools
from abjad.tools import markuptools
from abjad.tools import pitchtools


instruments = datastructuretools.TypedOrderedDict(
    [
        (
            'baritone saxophone',
            instrumenttools.BaritoneSaxophone(
                instrument_name='baritone saxophone',
                short_instrument_name='bar. sax.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Baritone', 'saxophone']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bar.', 'sax.']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C2, Ab4]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('ef,'),
                ),
            ),
        (
            'bass clarinet',
            instrumenttools.BassClarinet(
                instrument_name='bass clarinet',
                short_instrument_name='bass cl.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bass', 'clarinet']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bass', 'cl.']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        indicatortools.Clef(
                            name='bass',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[Bb1, G5]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('bf,'),
                ),
            ),
        (
            'bass flute',
            instrumenttools.BassFlute(
                instrument_name='bass flute',
                short_instrument_name='bass fl.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bass', 'flute']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bass', 'fl.']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C3, C6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('c'),
                ),
            ),
        (
            'cello',
            instrumenttools.Cello(
                instrument_name='cello',
                short_instrument_name='vc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Cello'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Vc.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='bass',
                            ),
                        indicatortools.Clef(
                            name='tenor',
                            ),
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                default_tuning=indicatortools.Tuning(
                    pitches=pitchtools.PitchSegment(
                        (
                            pitchtools.NamedPitch('c,'),
                            pitchtools.NamedPitch('g,'),
                            pitchtools.NamedPitch('d'),
                            pitchtools.NamedPitch('a'),
                            ),
                        item_class=pitchtools.NamedPitch,
                        ),
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C2, G5]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'clarinet in B-flat',
            instrumenttools.ClarinetInBFlat(
                instrument_name='clarinet in B-flat',
                short_instrument_name='cl. in B-flat',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Clarinet'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Cl.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[D3, Bb6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('bf'),
                ),
            ),
        (
            'contrabass',
            instrumenttools.Contrabass(
                instrument_name='contrabass',
                short_instrument_name='cb.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Contrabass'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Cb.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='bass',
                            ),
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                default_tuning=indicatortools.Tuning(
                    pitches=pitchtools.PitchSegment(
                        (
                            pitchtools.NamedPitch('c,,'),
                            pitchtools.NamedPitch('a,,'),
                            pitchtools.NamedPitch('d,'),
                            pitchtools.NamedPitch('g,'),
                            ),
                        item_class=pitchtools.NamedPitch,
                        ),
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C1, G4]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('c'),
                ),
            ),
        (
            'English horn',
            instrumenttools.EnglishHorn(
                instrument_name='English horn',
                short_instrument_name='Eng. hn.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['English', 'horn']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Eng.', 'hn.']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[E3, C6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('f'),
                ),
            ),
        (
            'flute',
            instrumenttools.Flute(
                instrument_name='flute',
                short_instrument_name='fl.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Flute'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Fl.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C4, D7]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'guitar',
            instrumenttools.Guitar(
                instrument_name='guitar',
                short_instrument_name='gt.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Guitar'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Gt.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                default_tuning=indicatortools.Tuning(
                    pitches=pitchtools.PitchSegment(
                        (
                            pitchtools.NamedPitch('e,'),
                            pitchtools.NamedPitch('a,'),
                            pitchtools.NamedPitch('d'),
                            pitchtools.NamedPitch('g'),
                            pitchtools.NamedPitch('b'),
                            pitchtools.NamedPitch("e'"),
                            ),
                        item_class=pitchtools.NamedPitch,
                        ),
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[E2, E5]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch('c'),
                ),
            ),
        (
            'oboe',
            instrumenttools.Oboe(
                instrument_name='oboe',
                short_instrument_name='ob.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Oboe'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Ob.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[Bb3, A6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'percussion',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Percussion'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Perc.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'piano',
            instrumenttools.Piano(
                instrument_name='piano',
                short_instrument_name='pf.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Piano'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Pf.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        indicatortools.Clef(
                            name='bass',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'piccolo',
            instrumenttools.Piccolo(
                instrument_name='piccolo',
                short_instrument_name='picc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Piccolo'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Picc.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[D5, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c''"),
                ),
            ),
        (
            'sopranino saxophone',
            instrumenttools.SopraninoSaxophone(
                instrument_name='sopranino saxophone',
                short_instrument_name='sopranino sax.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Sopranino', 'saxophone']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Sopr.', 'sax.']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[Db4, F#6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("ef'"),
                ),
            ),
        (
            'viola',
            instrumenttools.Viola(
                instrument_name='viola',
                short_instrument_name='va.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Viola'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Va.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='alto',
                            ),
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                default_tuning=indicatortools.Tuning(
                    pitches=pitchtools.PitchSegment(
                        (
                            pitchtools.NamedPitch('c'),
                            pitchtools.NamedPitch('g'),
                            pitchtools.NamedPitch("d'"),
                            pitchtools.NamedPitch("a'"),
                            ),
                        item_class=pitchtools.NamedPitch,
                        ),
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[C3, D6]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'violin',
            instrumenttools.Violin(
                instrument_name='violin',
                short_instrument_name='vn.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Violin'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Vn.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        ]
                    ),
                default_tuning=indicatortools.Tuning(
                    pitches=pitchtools.PitchSegment(
                        (
                            pitchtools.NamedPitch('g'),
                            pitchtools.NamedPitch("d'"),
                            pitchtools.NamedPitch("a'"),
                            pitchtools.NamedPitch("e''"),
                            ),
                        item_class=pitchtools.NamedPitch,
                        ),
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[G3, G7]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        ]
    )