# -*- encoding: utf-8 -*-
from abjad.tools import datastructuretools
from abjad.tools import indicatortools
from abjad.tools import instrumenttools
from abjad.tools import markuptools
from abjad.tools import pitchtools


percussion_instruments = datastructuretools.TypedOrderedDict(
    [
        (
            'almglocken',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'almglocken'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'alm.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'bass drum',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Bass', 'drum']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'BD'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'castanets',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'castanets'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'cast.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'caxixi',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'caxixi'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'cxi.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'guiro',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Guiro'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'gro.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'large China cymbal',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Large', 'China', 'cymbal']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Ch.', 'cym.', '(L)']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'large tam-tam',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Large', 'tam-tam']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['tam.', '(L)']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'maracas',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'maracas'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'mrcs.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'marimba',
            instrumenttools.Marimba(
                instrument_name='marimba',
                short_instrument_name='mb.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Marimba'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'Mb.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='treble',
                            ),
                        indicatortools.Clef(
                            name='bass',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[F2, C7]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'snare drum',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Snare', 'drum']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'SD'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'Tibetan bowl',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Tibetan', 'bowl']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Tib.', 'bowl']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'triangle',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            'Triangle'
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            'tri.'
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'very large China cymbal',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Very', 'large', 'China', 'cymbal']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Ch.', 'cym.', '(XL)']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'very large tam-tam',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Very', 'large', 'tam-tam']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['tam.', '(XL)']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        (
            'whirly tube',
            instrumenttools.Percussion(
                instrument_name='percussion',
                short_instrument_name='perc.',
                instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            16,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['Whirly', 'tube']
                                )
                            ),
                        ),
                    ),
                short_instrument_name_markup=markuptools.Markup(
                    contents=(
                        markuptools.MarkupCommand(
                            'hcenter-in',
                            10,
                            markuptools.MarkupCommand(
                                'center-column',
                                ['whr.', 'tube']
                                )
                            ),
                        ),
                    ),
                allowable_clefs=indicatortools.ClefInventory(
                    [
                        indicatortools.Clef(
                            name='percussion',
                            ),
                        ]
                    ),
                pitch_range=pitchtools.PitchRange(
                    range_string='[A0, C8]',
                    ),
                sounding_pitch_of_written_middle_c=pitchtools.NamedPitch("c'"),
                ),
            ),
        ]
    )