import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Wind_Section_Staff_Group',
                'Flute_Music_Staff',
                'Flute_Music_Voice',
                'OboeMusicStaff',
                'Oboe_Music_Voice',
                'Clarinet_Music_Staff',
                'Clarinet_Music_Voice',
                'Saxophone_Music_Staff',
                'Saxophone_Music_Voice',
                'Percussion_Section_Staff_Group',
                'Guitar_Music_Staff',
                'Guitar_Music_Voice',
                'Piano_Music_Staff',
                'Piano_Music_Voice',
                'PercussionMusicStaff',
                'Percussion_Music_Voice',
                'String_Section_Staff_Group',
                'Violin_Music_Staff',
                'Violin_Music_Voice',
                'Viola_Music_Staff',
                'Viola_Music_Voice',
                'CelloMusicStaff',
                'Cello_Music_Voice',
                'Contrabass_Music_Staff',
                'Contrabass_Music_Voice',
                ],
            ),
        ('duration', "1'46''"),
        ('final_measure_number', 44),
        ('first_measure_number', 1),
        ('segment_name', '_'),
        ('segment_number', 1),
        ('start_clock_time', "0'00''"),
        ('stop_clock_time', "1'46''"),
        (
            'time_signatures',
            [
                '2/4',
                '2/4',
                '6/4',
                '3/4',
                '4/4',
                '6/8',
                '4/4',
                '5/4',
                '4/4',
                '3/4',
                '4/4',
                '5/4',
                '6/8',
                '2/4',
                '6/4',
                '2/4',
                '5/4',
                '6/8',
                '4/4',
                '6/4',
                '2/4',
                '2/4',
                '3/4',
                '4/4',
                '2/4',
                '2/4',
                '6/4',
                '4/4',
                '3/4',
                '6/8',
                '4/4',
                '5/4',
                '3/4',
                '4/4',
                '4/4',
                '5/4',
                '6/8',
                '2/4',
                '6/4',
                '2/4',
                '5/4',
                '6/8',
                '4/4',
                '6/4',
                ],
            ),
        ]
    )
