import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "1'52''"),
        ('final_measure_number', 74),
        ('first_measure_number', 45),
        ('phantom', True),
        ('segment_name', 'A'),
        ('segment_number', 2),
        ('start_clock_time', "1'47''"),
        ('stop_clock_time', "3'39''"),
        (
            'time_signatures',
            [
                '2/4',
                '2/4',
                '6/4',
                '3/4',
                '4/4',
                '6/8',
                '4/4',
                '5/4',
                '4/4',
                '3/4',
                '4/4',
                '5/4',
                '6/8',
                '2/4',
                '6/4',
                '2/4',
                '5/4',
                '6/8',
                '4/4',
                '6/4',
                '2/4',
                '2/4',
                '3/4',
                '4/4',
                '2/4',
                '2/4',
                '6/4',
                '4/4',
                '3/4',
                '6/8',
                ],
            ),
        ]
    )
