# -*- encoding: utf-8 -*-
from abjad.tools import pitchtools


violin_halo_pitches = [
    pitchtools.NamedPitch("g'"),
    pitchtools.NamedPitch("af'"),
    pitchtools.NamedPitch("gqs'"),
    pitchtools.NamedPitch("a'"),
    pitchtools.NamedPitch("bqf'"),
    pitchtools.NamedPitch("af'"),
    pitchtools.NamedPitch("gqs'"),
    pitchtools.NamedPitch("a'"),
    pitchtools.NamedPitch("g'"),
    pitchtools.NamedPitch("a'"),
    pitchtools.NamedPitch("b'"),
    pitchtools.NamedPitch("aqs'"),
    pitchtools.NamedPitch("bf'"),
    pitchtools.NamedPitch("g'"),
    pitchtools.NamedPitch("a'"),
    pitchtools.NamedPitch("b'"),
    pitchtools.NamedPitch("aqs'"),
    pitchtools.NamedPitch("cqf''"),
    pitchtools.NamedPitch("bf'"),
    pitchtools.NamedPitch("c''"),
    pitchtools.NamedPitch("g'"),
    pitchtools.NamedPitch("c''"),
    pitchtools.NamedPitch("bqf'"),
    pitchtools.NamedPitch("cqs''"),
    pitchtools.NamedPitch("d''"),
    pitchtools.NamedPitch("b'"),
    pitchtools.NamedPitch("c''"),
    pitchtools.NamedPitch("dqf''"),
    pitchtools.NamedPitch("ef''"),
    pitchtools.NamedPitch("c''"),
    pitchtools.NamedPitch("dqf''"),
    pitchtools.NamedPitch("etqf''"),
    pitchtools.NamedPitch("d''"),
    ]