# -*- encoding: utf-8 -*-
from abjad.tools import datastructuretools
from abjad.tools import indicatortools


time_signatures = datastructuretools.CyclicTuple(
    [
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((5, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((3, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((2, 4)),
        indicatortools.TimeSignature((4, 4)),
        indicatortools.TimeSignature((2, 4)),
        ]
    )