import abjad


metadata = abjad.OrderedDict(
    [
        ('duration', "1'50''"),
        ('final_measure_number', 111),
        ('first_measure_number', 75),
        ('segment_name', 'B'),
        ('segment_number', 3),
        ('start_clock_time', "3'37''"),
        ('stop_clock_time', "5'27''"),
        (
            'time_signatures',
            [
                '2/4',
                '2/4',
                '6/4',
                '3/4',
                '4/4',
                '6/8',
                '4/4',
                '5/4',
                '4/4',
                '3/4',
                '4/4',
                '5/4',
                '6/8',
                '2/4',
                '6/4',
                '2/4',
                '5/4',
                '6/8',
                '4/4',
                '6/4',
                '2/4',
                '2/4',
                '3/4',
                '4/4',
                '2/4',
                '2/4',
                '6/4',
                '4/4',
                '3/4',
                '6/8',
                '4/4',
                '5/4',
                '3/4',
                '4/4',
                '4/4',
                '5/4',
                '6/8',
                ],
            ),
        ]
    )
